version: '3'

image: snibox/snibox:latest
    command: sh -c "rm -rf tmp/pids && ./bin/rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      FORCE_SSL: "${FORCE_SSL}"
      MAILGUN_SMTP_PORT: "${MAILGUN_SMTP_PORT}"
      MAILGUN_SMTP_SERVER: "${MAILGUN_SMTP_SERVER}"
      MAILGUN_SMTP_LOGIN: "${MAILGUN_SMTP_LOGIN}"
      MAILGUN_SMTP_PASSWORD: "${MAILGUN_SMTP_PASSWORD}"
      MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"
      MAILGUN_PUBLIC_KEY: "${MAILGUN_PUBLIC_KEY}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=standardfile"
      - "traefik.frontend.rule=Host:url"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=url"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - static-files:/app/public
    depends_on:
      - database

  database:
    image: postgres:10.7-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  static-files:
